### ISSUE TITLE
Warning : Max Listeners Exceeded

### ISSUE THREAD

**Issue by Carje4cs** [jamieweavis/dodgem#5]
Since v0.2.13, most of the trades fails to bump and sometimes i get this error:

> (node:7052) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 response listeners added. Use emitter.setMaxListeners() to increase limit.

Edit: Now i'm getting this error after user log in or when trying to bump:
> (node:6232) UnhandledPromiseRejectionWarning: Error: SSL Certificate error: ERR_CERT_DATE_INVALID
    at NavigatorWatcher.waitForNavigation (\dodgem\node_modules\puppeteer\lib\NavigatorWatcher.js:74:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:6232) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6232) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I have reinstalled dodgem and node js, and also tried with different versions, but with no luck.

**Comment by jamieweavis** [comment]
Thank you for reporting this issue.

I'm not going to have time to look at this for a while - for the time being you can install the previous version with the following command:

```sh
# Via yarn
$ yarn global add dodgem@0.2.12

# Via npm
$ npm install --global dodgem@0.2.12
```

**Comment by jamieweavis** [comment]
@Carje4cs I've just pushed out v0.3.0, could you please update and let me know if you are still having this issue?

**Comment by Carje4cs** [comment]
v0.3.0
No errors showing up, but it only find and bumps 3 trades, no matter how many i have.
I have completely uninstalled and installed and it didn't resolved the issue.

Since v0.2.13 you replaced the command `bump all/oldest time` with `start` which prevents the user to run it through a .bat file, because now it requires user interaction. I have managed to get around this by editing the dodgem.js file from : `C:\Users\<User>\AppData\Roaming\npm\node_modules\dodgem\src\` with the following:

- Removed the code from `// Bump target & interval prompt`

- Changed `this.interval` to actual time, eg: `20` on the next lines: -

- -

**Comment by Carje4cs** [comment]
v0.3.0
No errors showing up, but it only find and bump 3 trades, no matter how many i have.
I have completely uninstalled and installed and it didn't solved the issue.

Since v0.2.13 you replaced the command `bump all/oldest time` with `start` which prevents the user to run it through a .bat file, because now it requires user interaction. I have managed to get around this by editing the dodgem.js file from : `C:\Users\<User>\AppData\Roaming\npm\node_modules\dodgem\src\` with the following:

* Removed the code from `// Bump target & interval prompt` lines #27 - #49
* Changed `this.interval` to actual time, eg: `20` on the next lines:
  * _#56_ new Ora(\`Bumping ${chalk.blue(target)} every ${chalk.blue(`this.interval`)} minutes\`).info()
  * _#174_ const minutes = 1000 * 60 * `this.interval`
  * _#175_ const nextRunTs = moment().add(`this.interval`, 'minutes').format('HH:mm:ss')
> ↑ This will bump all your trades every 20 minutes with `start` command ↑

In v0.3.0, the dodgem.js file was reworked and i couldn't manage to bypass the user interaction.

**Comment by jamieweavis** [comment]
> No errors showing up, but it only find and bump 3 trades, no matter how many i have.
I have completely uninstalled and installed and it didn't solved the issue.

That's strange - I've just tested with 4 trades and it seems to be working:
<img src="https://i.imgur.com/ngY8eM6.png" width=300>

Could I ask which version of `node` you are running?

> Since v0.2.13 you replaced the command bump all/oldest time with start which prevents the user to run it through a .bat file, because now it requires user interaction.

That's interesting, I didn't think of people using `dodgem` like that. I'm happy to re-implement the `bump` command for more advanced users. I switched the `bump` command for the `start` command to be more user friendly, considering most people using this tool may not be that comfortable at the command line.

I will look into the issue that you have mentioned and I will re-add the `bump` command too.

**Comment by Carje4cs** [comment]
Just to know, i have more than 10 active trades, in case this affects somehow.
Node `v8.11.1` (Carbon)
npm `v5.6.0`

**Comment by jamieweavis** [comment]
I will try and look into this within the next few days, you could install the older version for now until I release a fix.

The amount of trades could potentially be the issue, I have a feeling it's because RLG is so slow and sluggish. I'll keep you updated with my progress.

**Comment by jamieweavis** [comment]
Hey @Carje4cs, I've just pushed update `v0.3.1`.

I've fixed the issue where only 3 active trades would be detected, I've also had a bit of a breakthrough with puppeteer which has considerably increased the speed of dodgem!

I'm going to close this issue for now, if you get the "max listener" error again then feel free to re-open this issue.

Thank you for your feedback and helping to make dodgem better, if you have any other issues please open a new issue - I will be working on adding the `bump` command again soon so that you can trigger dodgem via `.bat` file.

**Comment by jamieweavis** [comment]
I've raised a new issue for the `bump` command which can be followed at #6.
