### ISSUE TITLE
Reimplement `bump` command for advanced users

### ISSUE THREAD

**Issue by jamieweavis** [jamieweavis/dodgem#6]
**As an** advanced user of `dodgem`
**I would like** to use `dodgem` without user input
**So that** I can trigger `dodgem` via `.bat` file

---

Suggested solution is to reimplement the `bump` command with `target` and `interval` arguments, which was removed in favour of new user friendly, wizard driven `start` command.

Bringing back the `bump` command as an additional command for more advanced users, whilst keeping the new `start` command for less advanced users seems like a good solution.

**Comment by Carje4cs** [comment]
Any news?

**Comment by jamieweavis** [comment]
I haven't had time to work on dodgem recently, this will be the first issue I resolve when I do.

In the meantime, I'm open to pull requests if someone else wants to pick this up.

**Comment by jamieweavis** [comment]
@Carje4cs sorry for the wait, but I've just pushed `v0.4.0` which reimplements this feature 🎉

**Comment by jamieweavis** [comment]
Great, thanks for that!
