### ISSUE TITLE
Editing listings locally

### ISSUE THREAD

**Issue by kennklam** [jamieweavis/dodgem#8]
**As a** user of dodgem
**I would like** to edit rocket league listings locally to be updated on the next bump
**So that** I don't have to manually make any changes that need to made after the 15 minute wait time

I hope that was clear enough, not sure if it is out of scope or if it is manageable but it would be really helpful for me. I make a lot of trades and it requires a lot of listings to change as items come and go. With my memory I tend to forget often. Preferably I would like to make the change right after I make my trade so I won't have to wait till the listing goes past the 15 minute mark before making the edit.

Thanks!

**Comment by jamieweavis** [comment]
Thanks for the feature request, unfortunately Dodgem is being archived - please see the README for more information.
