### ISSUE TITLE
Privacy Policy Update

### ISSUE THREAD

**Issue by Carje4cs** [jamieweavis/dodgem#9]
RL website has currently updated their Privacy Policy and now requires to ACCEPT the new terms in order to login.

**Comment by jamieweavis** [comment]
Thanks for reporting this @Carje4cs. I'll look into fixing this now and pushing a minor update.

**Comment by jamieweavis** [comment]
@Carje4cs this has been fixed in `v0.3.2`.

Thanks again for reporting the issue - I haven't been playing Rocket League recently, and therefore I'm not using dodgem, so I would have never known 👍
